version: '3.5'

services:

  restic-api:
    build: .
    ports:
      - 8080:8080
    environment:
      - RESTIC_PASSWORD=123
      - LOG_LEVEL=debug
      - PRE_BACKUP_COMMAND=/pre-test.sh
      - POST_BACKUP_COMMAND=/post-test.sh

